using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace project_GVEncheva22.Models
{
    // Base class for all entities in the system.
    // Provides common properties like Id and CreatedAt.
    public class BaseEntity
    {
         // Primary key - automatically generated by the database.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        // Stores the date and time when the entity was created
        // Used for tracking and sorting records
        [DataType(DataType.DateTime)]
        public DateTime CreatedAt { get; set; }
    }
}